export interface GlossaryMetric {
  key: string
  category: string
  arabicName: string
  englishName: string
  aliases: string[]
  definition: string
  formula: string
  formulaExplanation: string
  whyImportant: string[]
  benchmarks: { platform: string; range: string }[]
  interpretation: { high: string; low: string }
  howToImprove: string[]
  relatedMetrics: string[]
  commonMistakes: string[]
  proTip: string
}

export type MetricCategory = "cost" | "performance" | "profitability" | "efficiency" | "engagement" | "reach"

export const categoryLabels: Record<MetricCategory, string> = {
  cost: "مقاييس التكلفة",
  performance: "مقاييس الأداء",
  profitability: "مقاييس الربحية",
  efficiency: "مقاييس الكفاءة",
  engagement: "مقاييس التفاعل",
  reach: "مقاييس الوصول",
}

export const metricsGlossary: Record<string, GlossaryMetric> = {
  spend: {
    key: "spend",
    category: "cost",
    arabicName: "إجمالي الإنفاق",
    englishName: "Total Spend",
    aliases: ["Cost","Ad Spend","Amount Spent","الإنفاق","المصاريف","التكلفة"],
    definition: "المبلغ الإجمالي الذي تم إنفاقه على الحملات الإعلانية خلال فترة زمنية محددة. يشمل كل قرش تم دفعه للمنصة مقابل عرض الإعلانات.",
    formula: "مجموع تكلفة جميع الإعلانات = Bid x مرات الظهور (حسب نموذج التسعير)",
    formulaExplanation: "يتم احتساب الإنفاق بناءً على نموذج التسعير: CPC, CPM, أو CPA. تختلف التكلفة حسب المنافسة والموسم والصناعة.",
    whyImportant: ["يمثل حجم الاستثمار في الإعلانات وأساس كل حسابات الربحية","بدون تتبع الإنفاق لا يمكن حساب ROAS أو CPA","يساعد في تحديد الميزانية المثلى","مؤشر قابلية التوسع","أساس لحساب معظم المقاييس الأخرى"],
    benchmarks: [{ platform: "Meta Ads", range: "500-50,000$ شهرياً" },{ platform: "Google Ads", range: "1,000-100,000$ شهرياً" },{ platform: "TikTok Ads", range: "200-20,000$ شهرياً" },{ platform: "Snapchat Ads", range: "300-15,000$ شهرياً" }],
    interpretation: { high: "إنفاق مرتفع = استثمار كبير. يحتاج مراقبة دقيقة للعائد.", low: "إنفاق منخفض = مرحلة اختبار أو ميزانية محدودة." },
    howToImprove: ["وزع الميزانية على أفضل الحملات أداءً","استخدم Daily Budget بدلاً من Lifetime Budget","راقب معدل حرق الميزانية","حدد Bid Cap للتحكم في التكلفة","أوقف الحملات الخاسرة فوراً"],
    relatedMetrics: ["roas","cpa","cpm","cpc","profit"],
    commonMistakes: ["الخلط بين الإنفاق (Spend) و CPM","توزيع الميزانية بالتساوي","عدم تتبع الإنفاق على مستوى الكيان"],
    proTip: "استخدم قاعدة 80/20: 80% من ميزانيك للحملات المثبتة و 20% للاختبار. راجع التوزيع أسبوعياً.",
  },
  revenue: {
    key: "revenue",
    category: "performance",
    arabicName: "الإيرادات",
    englishName: "Revenue",
    aliases: ["Sales","Conversion Value","Purchase Value","المبيعات","قيمة التحويلات"],
    definition: "إجمالي قيمة المبيعات المنسوبة للحملات الإعلانية. يتم تتبعها عبر Pixel أو Conversions API.",
    formula: "مجموع قيم التحويلات المنسوبة = سعر المنتج x عدد المشتريات",
    formulaExplanation: "تعتمد الإيرادات على إعداد التتبع. يوصى باستخدام CAPI (Conversions API) لتعويض فقدان البيكسل.",
    whyImportant: ["الهدف النهائي لأي حملة","بدون إيرادات دقيقة لا يمكن حساب ROAS","تساعد في تحديد الجمهور الأكثر قيمة","تمكن من اتخاذ قرارات التوسع","مؤشر نجاح المنظومة التسويقية"],
    benchmarks: [{ platform: "Meta Ads", range: "هدف 3x-5x من الإنفاق" },{ platform: "Google Ads", range: "Search أعلى إيرادات" },{ platform: "TikTok Ads", range: "أقل لكن تكلفة اكتساب أقل" },{ platform: "Snapchat", range: "مناسبة للموضة والجمال" }],
    interpretation: { high: "إيرادات عالية = مبيعات قوية. افحص هامش الربح.", low: "إيرادات منخفضة = المشكلة في الإعلان، الصفحة، أو المنتج." },
    howToImprove: ["حسن مسار التحويل","اختبر عروض مختلفة","حسن تجربة الدفع","أضف Upsell/Cross-sell","استخدم Retargeting"],
    relatedMetrics: ["roas","profit","conversions","cpa"],
    commonMistakes: ["عدم تتبع الإيرادات بدقة","الاعتماد على آخر نقرة فقط","الخلط بين Revenue و Profit"],
    proTip: "استخدم نافذة إحالة 7 أيام للنقرات و 1 للظهور. للمنتجات ذات الدورة الطويلة، زدها لـ14-28 يوماً.",
  },
  roas: {
    key: "roas",
    category: "profitability",
    arabicName: "العائد على الإنفاق الإعلاني",
    englishName: "Return on Ad Spend (ROAS)",
    aliases: ["ROI","Return on Investment","Ad Efficiency","العائد","كفاءة الإنفاق"],
    definition: "أهم مقياس ربحية. يوضح كم تربح مقابل كل ما تنفقه على الإعلانات. ROAS = 5 يعني كل 1 جنيه رجعلك 5.",
    formula: "ROAS = إجمالي الإيرادات ÷ إجمالي الإنفاق الإعلاني",
    formulaExplanation: "مثال: أنفقت 10,000 وحققت 50,000، الـ ROAS = 5. الفرق عن ROI: ROI يشمل كل التكاليف. نقطة التعادل = 1 / هامش الربح.",
    whyImportant: ["يحدد إذا كانت الحملات مربحة","يساعد في قرارات التوسع أو الإيقاف","يقارن أداء الحملات بغض النظر عن الميزانية","يحدد نقطة التعادل لكل منتج","أساس تحديد الميزانية"],
    benchmarks: [{ platform: "Meta Ads", range: "2.5x-5x جيد، 5x+ ممتاز" },{ platform: "Google Ads", range: "3x-6x للبحث، 2x-4x للتسوق" },{ platform: "TikTok Ads", range: "2x-4x مقبول، 4x+ ممتاز" },{ platform: "Snapchat", range: "2x-3.5x" }],
    interpretation: { high: "ROAS > 4x: ممتاز. فرصة للتوسع مع مراقبة التكرار.", low: "ROAS < 1.5x: خطر. افحص الاستهداف والإعلان والصفحة المقصودة." },
    howToImprove: ["زود الإيرادات لكل زائر","قلل الإنفاق الضائع","ارفع متوسط قيمة الطلب (AOV)","حسن الاستهداف","استخدم إعلانات التحويل"],
    relatedMetrics: ["revenue","spend","cpa","profit","conversionRate"],
    commonMistakes: ["التركيز على ROAS بدون هامش الربح","مقارنة ROAS عبر صناعات مختلفة","عدم حساب التكاليف الخفية"],
    proTip: "اعرف نقطة التعادل: لو هامش الربح 40%، نقطة التعادل = 2.5x. أي ROAS أقل من 2.5x = خسارة.",
  },
  cpa: {
    key: "cpa",
    category: "efficiency",
    arabicName: "تكلفة الاكتساب",
    englishName: "Cost Per Acquisition (CPA)",
    aliases: ["Cost Per Action","Cost Per Conversion","Cost Per Result","تكلفة التحويل"],
    definition: "متوسط التكلفة للحصول على تحويل واحد (مشتري، مشترك). المقياس الأهم لكفاءة الحملة - كلما قل كان أفضل.",
    formula: "CPA = إجمالي الإنفاق ÷ عدد التحويلات",
    formulaExplanation: "مثال: أنفقت 5,000 وحققت 50 تحويل = CPA 100. الـ CPA المثالي يعتمد على LTV (قيمة العميل مدى الحياة).",
    whyImportant: ["يقيس كفاءة الحملة","يساعد في تحديد ربحية القنوات","أساس حساب العائد على الاستثمار","مقارنة أداء الحملات","يحدد جدوى التوسع"],
    benchmarks: [{ platform: "Meta Ads", range: "e-commerce -50, SaaS -200" },{ platform: "Google Ads", range: "Search أقل CPA" },{ platform: "TikTok Ads", range: "عادة أقل تكلفة" },{ platform: "Snapchat", range: "متوسط" }],
    interpretation: { high: "CPA عالي = كل عميل مكلف. احتاج تحسين.", low: "CPA منخفض = كفاءة عالية. استمر وابحث عن توسع." },
    howToImprove: ["حسن الاستهداف","حسن الصفحة المقصودة","اختبر عروضاً مختلفة","استخدم Custom Audiences","حسن Exclusion Lists"],
    relatedMetrics: ["roas","conversionRate","spend","conversions"],
    commonMistakes: ["مقارنة CPA عبر صناعات مختلفة","التركيز على خفض CPA على حساب الجودة","عدم حساب LTV مع CPA"],
    proTip: "CPA المثالي < 30% من LTV. لو LTV = 500، CPA مقبول حتى 150. لا تضحي بالجودة عشان CPA رخيص.",
  },
  ctr: {
    key: "ctr",
    category: "engagement",
    arabicName: "نسبة النقر إلى الظهور",
    englishName: "Click-Through Rate (CTR)",
    aliases: ["Click Rate","نسبة النقر","معدل النقر"],
    definition: "نسبة الأشخاص الذين شاهدوا الإعلان ثم نقروا عليه. يعكس جاذبية الإعلان وملاءمته للجمهور.",
    formula: "CTR = (Clicks / Impressions) x 100",
    formulaExplanation: "مثال: 10,000 ظهور و 200 نقرة = CTR 2%. يعتمد على الهوك، صلة الإعلان بالجمهور، ونوع الإعلان.",
    whyImportant: ["مؤشر جاذبية الإعلان","يساعد في تقييم الهوك","كلما ارتفع قل CPC","يحدد تطابق الإعلان مع الجمهور","يساعد في تحسين الإعلانات قبل التوسع"],
    benchmarks: [{ platform: "Meta Ads", range: "0.5%-2% فيسبوك، 0.8%-3% إنستغرام" },{ platform: "Google Ads", range: "2%-6% للبحث، 0.3%-1% للعرض" },{ platform: "TikTok Ads", range: "1%-5%" },{ platform: "Snapchat", range: "0.5%-2%" }],
    interpretation: { high: "CTR > 3%: الإعلان ممتاز. الهوك قوي والاستهداف دقيق.", low: "CTR < 0.5%: الإعلان لا يجذب. غير الهوك والصورة." },
    howToImprove: ["اختبر هوكات مختلفة في أول 3 ثواني","استخدم صوراً عالية الجودة","طابق النص مع Pain Points","اختبر عروضاً مختلفة","حسن دقة الاستهداف"],
    relatedMetrics: ["cpc","impressions","clicks","cpm"],
    commonMistakes: ["مقارنة CTR عبر منصات مختلفة","التركيز على CTR بدون تحويلات","تغيير إعلان ناجح لانخفاض طفيف"],
    proTip: "أول 3 ثواني هي الأهم. استخدم Pattern Interrupts: حركة مفاجئة، سؤال صادم، أو نتيجة غير متوقعة.",
  },
  cpm: {
    key: "cpm",
    category: "cost",
    arabicName: "تكلفة الألف ظهور",
    englishName: "Cost Per Mille (CPM)",
    aliases: ["Cost Per Thousand","تكلفة الألف","سعر الألف ظهور"],
    definition: "تكلفة كل 1000 ظهور لإعلانك. يقيس تكلفة الوصول ويعكس المنافسة على الجمهور.",
    formula: "CPM = (Spend / Impressions) x 1000",
    formulaExplanation: "مثال: أنفقت 500$ على 100,000 ظهور = CPM 5$. يتأثر بالموسم، المنافسة، Relevance Score.",
    whyImportant: ["مؤشر المنافسة","يحدد كفاءة الوصول","يساعد في تقدير الميزانية","مهم لحملات الوعي","يختلف حسب الموسم"],
    benchmarks: [{ platform: "Meta Ads", range: "-15 الشرق الأوسط، -35 أمريكا" },{ platform: "Google Ads", range: "-10 للبحث، -20 للعرض" },{ platform: "TikTok Ads", range: "-8" },{ platform: "Snapchat", range: "-12" }],
    interpretation: { high: "CPM عالي = سوق تنافسي. وسع الاستهداف أو حسن Relevance Score.", low: "CPM منخفض = وصول بتكلفة منخفضة. فرصة للتوسع." },
    howToImprove: ["حسن Relevance Score","حسن الاستهداف","اختبر Placements مختلفة","استخدم Lookalike Audiences","حسن توقيت الإعلانات"],
    relatedMetrics: ["cpc","ctr","impressions","spend"],
    commonMistakes: ["الخوف من CPM المرتفع","مقارنة CPM عبر دول مختلفة","التركيز على خفض CPM على حساب الجودة"],
    proTip: "CPM عالي أحياناً = جمهور أفضل يشتري أكثر. راقب CPA مع CPM: لو CPM مرتفع بس CPA منخفض، الجمهور ممتاز.",
  },
  cpc: {
    key: "cpc",
    category: "cost",
    arabicName: "تكلفة النقرة",
    englishName: "Cost Per Click (CPC)",
    aliases: ["Pay Per Click","PPC","تكلفة الضغطة","سعر النقرة"],
    definition: "متوسط المبلغ المدفوع لكل نقرة. مهم في منصات البحث ومؤشر المنافسة على الكلمات المفتاحية.",
    formula: "CPC = إجمالي الإنفاق ÷ عدد النقرات",
    formulaExplanation: "مثال: 1,000$ على 500 نقرة = CPC 2$. يختلف حسب المنصة، الجمهور، الصناعة، وجودة الإعلان.",
    whyImportant: ["مؤشر تكلفة الزيارة","يساعد في تقدير الميزانية","يحدد ترتيب الإعلان في جوجل","يرتبط بجودة الإعلان","يختلف بين منصات البحث والاجتماعي"],
    benchmarks: [{ platform: "Meta Ads", range: ".30-.00" },{ platform: "Google Ads", range: ".50-.00 للبحث" },{ platform: "TikTok Ads", range: ".10-.80" },{ platform: "Snapchat", range: ".20-.50" }],
    interpretation: { high: "CPC عالي = سوق تنافسي. افحص إذا العائد يستحق.", low: "CPC منخفض = كفاءة عالية. فرصة لزيارات كثيرة بميزانية محدودة." },
    howToImprove: ["حسن Quality Score في جوجل","استخدم Long-tail Keywords","حسن Relevance Score في ميتا","اختبر Bid Strategies","استهدف جمهوراً محدداً"],
    relatedMetrics: ["cpm","ctr","spend","cpa"],
    commonMistakes: ["التركيز على خفض CPC فقط","مقارنة CPC عبر منصات بدون سياق","عدم حساب جودة الزيارات"],
    proTip: "في ميتا، اخفض CPC عبر تحسين Relevance Score. في جوجل، ركز على Quality Score.",
  },
  conversions: {
    key: "conversions",
    category: "performance",
    arabicName: "التحويلات",
    englishName: "Conversions",
    aliases: ["Results","Actions","Purchase","Sign-ups","النتائج","الإجراءات"],
    definition: "عدد الإجراءات المطلوبة التي أكملها المستخدمون (مشتريات، تسجيلات، تحميلات).",
    formula: "تحتسب عبر Pixel/API عند إتمام المستخدم للإجراء",
    formulaExplanation: "التحويل يختلف حسب الهدف: شراء، تسجيل، إضافة للسلة. مهم تحديد الهدف الصحيح للحملة.",
    whyImportant: ["الهدف النهائي","أساس حساب CPA ومعدل التحويل و ROAS","تحديد الحملات الفعالة","تحسين الحملات بالبيانات","أساس التوسع"],
    benchmarks: [{ platform: "Meta Ads", range: "يختلف بالصناعة" },{ platform: "Google Ads", range: "Search أعلى تحويلات" },{ platform: "TikTok Ads", range: "أقل لكن أقل تكلفة" },{ platform: "Snapchat", range: "مناسب للعلامات الشابة" }],
    interpretation: { high: "تحويلات كثيرة = الحملة ناجحة. افحص الجودة.", low: "تحويلات قليلة = حسن الصفحة المقصودة والعرض والاستهداف." },
    howToImprove: ["حسن الصفحة المقصودة","بسط عملية الدفع","اختبر عروضاً مختلفة","استخدم Retargeting","حسن سرعة الموقع"],
    relatedMetrics: ["cpa","conversionRate","revenue","spend"],
    commonMistakes: ["تتبع التحويل الخاطئ","الاكتفاء بالعدد بدون جودة","عدم تتبع مسار التحويل بالكامل"],
    proTip: "تتبع كل خطوات المسار: مشاهدة > سلة > دفع > شراء. هتعرف أين تفقد العملاء.",
  },
  conversionRate: {
    key: "conversionRate",
    category: "efficiency",
    arabicName: "معدل التحويل",
    englishName: "Conversion Rate (CVR)",
    aliases: ["CVR","Conversion %","نسبة التحويل","معدل الشراء"],
    definition: "نسبة الذين نقروا ثم أكملوا الإجراء المطلوب. مقياس فعالية الصفحة المقصودة والعرض.",
    formula: "CVR = (Conversions / Clicks) x 100",
    formulaExplanation: "مثال: 1,000 نقرة و 50 تحويل = CVR 5%. يعتمد على جودة الصفحة، وضوح العرض، سهولة الدفع.",
    whyImportant: ["يقيس فعالية الصفحة المقصودة","يرتبط بـ CPA و ROAS","يكشف نقاط الضعف","مؤشر جودة الزيارات","أساس تحسين CRO"],
    benchmarks: [{ platform: "Meta Ads", range: "1%-5% للتجارة الإلكترونية" },{ platform: "Google Ads", range: "3%-10% للبحث" },{ platform: "TikTok Ads", range: "0.5%-3%" },{ platform: "Snapchat", range: "1%-4%" }],
    interpretation: { high: "CVR > 5%: الصفحة ممتازة والعرض مناسب.", low: "CVR < 1%: المشكلة في الصفحة أو العرض أو جودة الزيارات." },
    howToImprove: ["حسن الصفحة المقصودة","بسط الدفع","أضف Social Proof","اختبر A/B Testing","حسن سرعة الموقع"],
    relatedMetrics: ["conversions","cpa","roas","cpc"],
    commonMistakes: ["مقارنة CVR عبر صناعات","تجاهل جودة الزيارات","عدم اختبار الصفحات"],
    proTip: "قاعدة 3 ثواني: في أول 3 ثواني يجب أن يعرف الزائر: ماذا تقدم، ولماذا يختارك، وماذا يفعل.",
  },
  frequency: {
    key: "frequency",
    category: "engagement",
    arabicName: "معدل التكرار",
    englishName: "Ad Frequency",
    aliases: ["Frequency","Avg Frequency","تكرار الإعلان","معدل الظهور"],
    definition: "متوسط عدد مرات ظهور الإعلان لنفس الشخص. مؤشر الإرهاق الإعلاني (Ad Fatigue).",
    formula: "Frequency = Impressions ÷ Reach",
    formulaExplanation: "مثال: 50,000 ظهور و 20,000 Reach = Frequency 2.5. Frequency عالي = انخفاض الأداء وارتفاع التكلفة.",
    whyImportant: ["مؤشر الإرهاق الإعلاني","يحدد موعد تغيير الإعلانات","يؤثر على CTR و CPA","مهم لتجربة المستخدم","يحدد متى تحديث الكريتيف"],
    benchmarks: [{ platform: "Meta Ads", range: "1-3 طبيعي، 3-5 مرتفع، 5+ خطر" },{ platform: "Google Ads", range: "1-2 للبحث، 2-4 للعرض" },{ platform: "TikTok Ads", range: "1-3" },{ platform: "Snapchat", range: "1-3" }],
    interpretation: { high: "Frequency > 4: إرهاق إعلاني. جدد الكريتيف أو وسع الجمهور.", low: "Frequency < 2: جمهور جديد. فرصة جيدة." },
    howToImprove: ["وسع الجمهور","جدد الكريتيف كل 3-7 أيام","استخدم Frequency Capping","دور الحملات","استخدم Dynamic Creative"],
    relatedMetrics: ["impressions","reach","ctr","cpa"],
    commonMistakes: ["ترك Frequency فوق 4","تغيير الإعلان الناجح قبل توسيع الجمهور","عدم استخدام Frequency Capping"],
    proTip: "قاعدة 3 مرات: أول مرة يرى، ثاني مرة يهتم، ثالث مرة يتخذ إجراء. بعدها جدد الإعلان.",
  },
  profit: {
    key: "profit",
    category: "profitability",
    arabicName: "صافي الربح",
    englishName: "Net Profit",
    aliases: ["Net Profit","Profit Margin","الربح الصافي","هامش الربح"],
    definition: "صافي الربح بعد خصم تكاليف الإعلانات من الإيرادات. المقياس الحقيقي لنجاح الحملة.",
    formula: "الربح = الإيرادات - الإنفاق الإعلاني - التكاليف الإضافية",
    formulaExplanation: "الفرق عن ROAS: Profit يشمل كل التكاليف. ممكن ROAS 5x والربح قليل بسبب تكاليف المنتج.",
    whyImportant: ["المقياس الحقيقي للنجاح","بدون حساب الربح ممكن تظن نفسك ناجح وأنت بتخسر","يحدد المنتجات الأكثر ربحية","أساس التوسع","مؤشر الاستدامة"],
    benchmarks: [{ platform: "Meta Ads", range: "10%-30% هامش ربح" },{ platform: "Google Ads", range: "15%-40%" },{ platform: "TikTok Ads", range: "5%-20%" },{ platform: "Snapchat", range: "10%-25%" }],
    interpretation: { high: "ربح إيجابي = الحملات مربحة. ابحث عن زيادة الهامش.", low: "ربح سلبي = بتخسر. ارفع الأسعار أو حسن الكفاءة." },
    howToImprove: ["زود AOV عبر Upsell","قلل التكاليف","حسن كفاءة الحملات","ارفع الأسعار","ركز على المنتجات عالية الهامش"],
    relatedMetrics: ["revenue","roas","spend","cpa"],
    commonMistakes: ["الخلط بين Revenue و Profit","تجاهل التكاليف الخفية","التركيز على ROAS فقط"],
    proTip: "احسب هامش الربح الحقيقي: سعر البيع - (المنتج + الشحن + الإعلانات + المصاريف). لو أقل من 20%، ركز على تحسينه.",
  },
  impressions: {
    key: "impressions",
    category: "reach",
    arabicName: "مرات الظهور",
    englishName: "Impressions",
    aliases: ["Views","Shows","ظهور","مشاهدات"],
    definition: "عدد مرات عرض الإعلان على الشاشة. كل مرة يظهر فيها الإعلان تحتسب ظهور.",
    formula: "تحتسب مرة كلما تم تحميل الإعلان وظهوره",
    formulaExplanation: "في ميتا، تحتسب بعد ظهور 50% من الإعلان. Impressions كثيرة + Clicks قليلة = الإعلان مش جذاب.",
    whyImportant: ["مقياس الوعي","أساس حساب CPM و CTR و Frequency","تقيم مدى الوصول","مهم لـ Branding","يكشف مشكلة في الإعلان أو الوصول"],
    benchmarks: [{ platform: "Meta Ads", range: "10,000-1,000,000+ شهرياً" },{ platform: "Google Ads", range: "حسب الكلمات" },{ platform: "TikTok Ads", range: "أعلى من المتوسط" },{ platform: "Snapchat", range: "جيد للشباب" }],
    interpretation: { high: "ظهور عالي = وصول واسع. افحص CTR.", low: "ظهور محدود = زد الميزانية أو وسع الاستهداف." },
    howToImprove: ["زود الميزانية اليومية","وسع الجمهور","حسن Relevance Score","اختبر أوقاتاً مختلفة","استخدم Placements متعددة"],
    relatedMetrics: ["reach","frequency","cpm","ctr"],
    commonMistakes: ["التركيز على Impressions فقط","الاعتقاد أن Impressions كثيرة = نجاح","عدم التمييز بين Impressions و Reach"],
    proTip: "الفرق: Impressions = مرات الظهور، Reach = الأشخاص الفريدين. Impression كثيرة + Reach قليل = Frequency عالي = إرهاق.",
  },
  clicks: {
    key: "clicks",
    category: "engagement",
    arabicName: "النقرات",
    englishName: "Clicks",
    aliases: ["Click-Throughs","نقر","ضغطات"],
    definition: "عدد المرات التي نقر فيها المستخدمون على الإعلان.",
    formula: "تحتسب كلما نقر المستخدم على رابط الإعلان",
    formulaExplanation: "الفرق: All Clicks يشمل إعجابات وتعليقات، Link Clicks = اللي توصل للموقع. Link Clicks هو المهم.",
    whyImportant: ["مؤشر الاهتمام","أساس حساب CPC و CTR","تحديد حجم الزيارات","تقييم جاذبية الإعلان","مهم لحملات Traffic"],
    benchmarks: [{ platform: "Meta Ads", range: "حسب الميزانية" },{ platform: "Google Ads", range: "Search أعلى" },{ platform: "TikTok Ads", range: "عالية" },{ platform: "Snapchat", range: "متوسط" }],
    interpretation: { high: "نقرات كثيرة = اهتمام. افحص جودة التحويل.", low: "نقرات قليلة = غير الهوك أو الجمهور." },
    howToImprove: ["حسن الهوك","استخدم CTA واضحاً","اختبر صوراً وفيديوهات","حسن الاستهداف","استخدم أسئلة"],
    relatedMetrics: ["ctr","cpc","impressions","conversions"],
    commonMistakes: ["التركيز على الكمية بدون الجودة","الخلط بين All Clicks و Link Clicks","شراء نقرات رخيصة من جمهور غير مناسب"],
    proTip: "Link Clicks هو المهم - اللي يوصل الزوار لموقعك. All Clicks يشمل التفاعلات الاجتماعية.",
  },
  reach: {
    key: "reach",
    category: "reach",
    arabicName: "الوصول",
    englishName: "Reach",
    aliases: ["Unique Reach","Unique Users","المستخدمين الفريدين","الجمهور"],
    definition: "عدد الأشخاص الفريدين الذين شاهدوا الإعلان. يختلف عن Impressions (كل مرة ظهور).",
    formula: "عدد المستخدمين الفريدين الذين عرض لهم الإعلان",
    formulaExplanation: "العلاقة: Impressions = Reach x Frequency. 100,000 ظهور و 40,000 Reach = Frequency 2.5.",
    whyImportant: ["يقيس الحجم الفعلي للجمهور","يساعد في حساب Frequency","مؤشر التوسع","مهم لبناء الوعي","يكشف تشبع السوق"],
    benchmarks: [{ platform: "Meta Ads", range: "حسب حجم الجمهور" },{ platform: "Google Ads", range: "حسب الكلمات" },{ platform: "TikTok Ads", range: "عالٍ" },{ platform: "Snapchat", range: "جيد للشباب" }],
    interpretation: { high: "Reach عالي = وصول واسع. فرصة لبناء الوعي.", low: "Reach محدود = الجمهور صغير أو الميزانية منخفضة." },
    howToImprove: ["وسع الجمهور","زود الميزانية","استخدم Lookalike Audiences","جدد الكريتيف","اختبر جماهير مختلفة"],
    relatedMetrics: ["impressions","frequency","cpm"],
    commonMistakes: ["الخلط بين Reach و Impressions","الاعتقاد أن Reach كبير = أداء جيد","عدم متابعة Reach اليومي"],
    proTip: "راقب Reach اليومي. لو ثابت رغم زيادة الميزانية، معناه وصلت لأقصى حجم جمهور. وسع الجمهور أو جدد الإعلان.",
  },
}
